name: urubu-do-pix-backend

services:
  api:
    image: junioradelsonst/urubu-do-pix-backend:latest
    ports:
      - 8080:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
