name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code 
    runs-on: ubuntu-latest
    outputs: 
      commit_hash: ${{ steps.get_commit_hash.outputs.commit_hash }}
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
    
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
        
      - name: Build with Maven
        run: ./mvnw package

      - name: Upload Quarkus Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: target/quarkus-app/

  docker: 
    name: Build and Push Docker Image 
    runs-on: ubuntu-latest
    needs: [checkout, build]
    env:
      commit_hash: ${{ needs.checkout.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Quarkus Artifacts
        uses: actions/download-artifact@v4
        with:
          name: quarkus-app
          path: target/quarkus-app/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.DOCKERHUB_USERNAME }}/urubu-do-pix-backend:${{ env.commit_hash }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/urubu-do-pix-backend:${{ env.commit_hash }}